name: Valgrind

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/implementations@3
      run: |
        sudo apt-get install valgrind
    - name: make test
      run: valgrind ./hello
